# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: geolocation-api

custom:
  stages:
    - dev
    - staging
    - prod
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true
  warmup:
    cleanFolder: false

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${self:provider.stage}-*

  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'us-west-1'}

plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-stage-manager

functions:
  fetchLocationData:
    handler: handler.fetchLocationData
    warmup: true
    events:
      - http:
          path: location
          method: get
          cors: true
